Craigslist-jr/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'categories#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  resources :categories, except: :destroy do
    resources :articles, except: :index
  end
end

Craigslist-jr/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Craigslist-jr/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category

  validates :title, :key, :content, :category_id, presence: true
end

Craigslist-jr/app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :destroy

  validates :name, presence: true
end

Craigslist-jr/app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  validates :name, :email, presence: true
end

Craigslist-jr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def require_user
    redirect_to '/login' unless current_user
  end

end

Craigslist-jr/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :require_user

  def new
    @article = Article.new
    @category = Category.find_by(id: params[:category_id])
  end

  def create
    @category = Category.find_by(id: params[:category_id])
    @article = @category.articles.new(article_params)
    @article.key = SecureRandom.hex(4)
    @articles = @category.articles

    if @article.save
      @article_key = @article.key
      render 'new'
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @category = Category.find_by(id: params[:category_id])
    @article = Article.find_by(key: params[:key])
    redirect_to @category unless @article

  end

  def update
    @category = Category.find_by(id: params[:category_id])
    @article = Article.find_by(id: params[:id])

    if @article.update(article_params)
      redirect_to category_article_path(@category, @article)
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find_by(id: params[:category_id])
    @articles = @category.articles
    @article = Article.find_by(id: params[:id])
    @article.destroy

    redirect_to @category
  end

  private
    def article_params
      params.require(:article).permit(:title, :content)
    end
end


# http://localhost:3000/categories/6/articles/14/edit?key=a445f552

Craigslist-jr/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find_by(id: params[:id])
    @articles = @category.articles
  end

  def edit
    @category = Category.find_by(id: params[:id])
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def update
    @category = Category.find_by(id: params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

end

Craigslist-jr/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      @errors = ["Invalid email or password."]
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

Craigslist-jr/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

Craigslist-jr/app/helpers/application_helper.rb
module ApplicationHelper
end

Craigslist-jr/app/helpers/articles_helper.rb
module ArticlesHelper
end

Craigslist-jr/app/helpers/categories_helper.rb
module CategoriesHelper
end

Craigslist-jr/app/helpers/sessions_helper.rb
module SessionsHelper
end

Craigslist-jr/app/helpers/users_helper.rb
module UsersHelper
end

Craigslist-jr/app/views/articles/_form.html.erb
<%= form_for([@category, @article]) do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

Craigslist-jr/app/views/articles/edit.html.erb
<h1>Edit Your Listing</h1>

<%= render 'form' %>


<%= link_to 'Destroy', category_article_path(@category, @article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

Craigslist-jr/app/views/articles/new.html.erb
<h2>Add a new listing:</h2>

<% if @article_key %>
  <h2>IMPORTANT!! The link to edit your article is:</h2>
  <p> http://localhost:3000/categories/<%= @category.id %>/articles/<%= @article.id %>/edit?key=<%= @article_key %> </p>
  <%= link_to 'Go to your article', category_article_path(@category, @article) %>

<% end %>

<%= render 'form' %>

Craigslist-jr/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.content %></p>

<%= link_to 'Back', category_path(@article.category) %>

Craigslist-jr/app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

Craigslist-jr/app/views/categories/edit.html.erb
<h1>Editing a Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

Craigslist-jr/app/views/categories/index.html.erb
<h1>Categories:</h1>

<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>

<%= link_to 'New category', new_category_path %>

Craigslist-jr/app/views/categories/new.html.erb
<h1>Add a New Category Here!!</h1>

<%= render 'form' %>

Craigslist-jr/app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<ul>
  <% @articles.each do |article| %>

      <li><%= link_to article.title, category_article_path(@category, article) %></li>

  <% end %>
</ul>



<%= link_to 'Back', categories_path %> |
<%= link_to 'Edit Category Name', edit_category_path %> |
<%= link_to 'Add New Listing', new_category_article_path(@category) %>

Craigslist-jr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CraigslistJr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <% if current_user %>
      Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
    <% else %>
      <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
    <% end %>

    <%= yield %>

  </body>
</html>

Craigslist-jr/app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %><br><br>
  Email: <%= f.text_field :email %><br><br>
  Password: <%= f.password_field :password %><br><br>
  Password Confirmation: <%= f.password_field :password_confirmation %><br><br>
  <%= f.submit "Submit" %>

<% end %>